// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dev.nemuki.infra.repository.mapper.sandbox

import java.time.LocalDateTime

data class MainSandboxDatum (
  val id: Int,
  val username: String,
  val email: String,
  val createdAt: LocalDateTime
)

