// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dev.nemuki.infra.repository.mapper.sandbox

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.time.LocalDateTime

interface Queries {
  @Throws(SQLException::class)
  fun getSandboxDataById(id: Int): MainSandboxDatum?
  
  @Throws(SQLException::class)
  fun listSandboxData(): List<MainSandboxDatum>
  
}

