# Original: https://songmu.jp/riji/entry/2022-08-05-git-pr-release.html
---
name: git-pr-release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories

      - name: Run the Action
        uses: devops-infra/action-pull-request@master
        id: create-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: release

      - run: gh pr comment $PR_URL --body "Hi from GitHub CLI"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ steps.create-pr.outputs.url }}
