# Original: https://songmu.jp/riji/entry/2022-08-05-git-pr-release.html
---
name: git-pr-release

on:
  push:
    branches:
    - main

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - run: gem install --no-document git-pr-release

      - run: |
          git-pr-release --squashed > git-pr-release.log
          echo "pr=$(cat git-pr-release.log | grep '^Updated pull request:' | awk '{print $4}')" >> $GITHUB_OUTPUT
        id: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: pr-release
          # GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release.erb
          TZ: Asia/Tokyo

      - run: gh pr comment $PR_URL --body "Hi from GitHub CLI"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ steps.git-pr-release.outputs.pr }}