# Original: https://songmu.jp/riji/entry/2022-08-05-git-pr-release.html
---
name: git-pr-release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Setup git-pr-release-go
        uses: odanado/setup-release@v0
        with:
          repository: odanado/git-pr-release-go

      - run: |
          set -x

          output=$(git-pr-release-go --from main --to release 2>&1)

          echo "$output"

          if [ "$output" =~ "Created new a pull request." ]; then
            echo "PR_NUMBER=$(echo "$output" | grep -oP '\d+$')" >> $GITHUB_ENV
          elif [ "$output" =~ "The pull request already exists." ]; then
            echo "PR_NUMBER=$(echo "$output" | grep -oP '\d+$')" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on the pull request
        if: env.PR_NUMBER != ''
        run: gh pr comment ${{ env.PR_NUMBER }} \
          --body "This pull request was created by [git-pr-release-go]"
