# Original: https://songmu.jp/riji/entry/2022-08-05-git-pr-release.html
---
name: git-pr-release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  THOR_SHELL: Basic

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Setup git-pr-release-go
        uses: odanado/setup-release@v0
        with:
          repository: odanado/git-pr-release-go

      - run: git-pr-release-go --from main --to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
